version: '3.5'

services:
  drone:
    networks:
    - web
    labels:
      traefik.enable: 'true'
      traefik.frontend.rule: 'Host:{{ url.split("/")[2] }}'
      traefik.frontend.headers.SSLRedirect: 'true'
      traefik.port: '80'
    volumes:
    - {{ home }}/data:/var/lib/drone
    environment:
{% for key, value in drone_env.items() %}
    - {{ key }}={{ value }}
{% endfor %}
    - VIRTUAL_HOST={{ url.split("/")[2] }}

networks:
  web:
    external:
      name: web
  drone:
