version: '3'

services:
  drone:
    image: drone/drone
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/drone:/data
    environment:
{% for key, value in drone_env.items() %}
    - {{ key }}={{ value }}
{% endfor %}

    labels:
    - traefik.enable=true
    - traefik.http.routers.drone.rule=Host(`{{ url.split("/")[2] }}`)
    - traefik.http.routers.drone.entrypoints=websecure
    - traefik.http.routers.drone.tls.certresolver=leresolver
    networks:
    - web

networks:
  web:
    external: true
