version: '3.5'

services:
  drone:
    image: drone/drone:1
    logging:
      driver: journald
    restart: unless-stopped
    volumes:
    - ./data:/data
    - /var/run/docker.sock:/var/run/docker.sock
    network_mode: bridge
