version: '3.5'

services:
  drone:
    labels:
      traefik.enable: 'true'
      traefik.frontend.rule: 'Host: {{ url.split("/")[2] }}'
      traefik.frontend.headers.SSLRedirect: 'true'
      traefik.port: '80'
    environment:
{% for key, value in drone_env.items() %}
    - {{ key }}={{ value }}
{% endfor %}
