---
# Ansible or BigSudo role to setup Drone-CI

- set_fact:
    home: /home/drone
  when: home is not defined

- include_role: name=yourlabs.remember

- name: Ensure docker was setup once on this host
  include_role: name=yourlabs.remember tasks_from=require_once
  vars: {rolename: yourlabs.docker}

- name: Setting up drone base environment variables
  set_fact:
    drone_env:
      VIRTUAL_HOST: '{{ url.split("/")[2] }}'
      DRONE_RUNNER_CAPACITY: '2'
      DRONE_SERVER_HOST: '{{ url.split("/")[2] }}'
      DRONE_SERVER_PROTO: '{{ url.split(":")[0] }}'
      DRONE_TLS_AUTOCERT: 'false'
      DRONE_OPEN: '{% if open %}true{% else %}false{% endif %}'
      DRONE_DEBUG: 'true'

- name: Setting up github environment variables
  when: backend == 'github'
  loop_control:
    loop_var: drone_item
  with_dict:
    DRONE_GITHUB_SERVER: '{{ github_url }}'
    DRONE_GITHUB_CLIENT_ID: '{{ github_id }}'
    DRONE_GITHUB_CLIENT_SECRET: '{{ github_secret }}'
  set_fact:
    drone_env: '{{ drone_env|combine({drone_item.key: drone_item.value}) }}'

- name: Setting up gitlab environment variables
  when: backend == 'gitlab'
  loop_control:
    loop_var: drone_item
  with_dict:
    DRONE_GITLAB_SERVER: '{{ gitlab_url }}'
    DRONE_GITLAB_CLIENT_ID: '{{ gitlab_id }}'
    DRONE_GITLAB_CLIENT_SECRET: '{{ gitlab_secret }}'
  set_fact:
    drone_env: '{{ drone_env|combine({drone_item.key: drone_item.value}) }}'

- name: Setting up letsencrypt variables
  when: letsencrypt_email|length
  loop_control:
    loop_var: drone_item
  with_dict:
    LETSENCRYPT_HOST: '{{ url.split("/")[2] }}'
    LETSENCRYPT_EMAIL: '{{ letsencrypt_email }}'
  set_fact:
    drone_env: '{{ drone_env|combine({drone_item.key: drone_item.value}) }}'

- name: Make home directory
  file:
    path: '{{ home }}'
    state: directory
    owner: root
    mode: '0755'

- name: Upload docker-compose.yml
  copy:
    src: '{{ role_path }}/docker-compose.yml'
    dest: '{{ home }}/docker-compose.yml'

- name: Start {{ home }}/docker-compose.yml
  docker_compose:
    project_src: '{{ home }}'
    restarted: yes

- include_role: name=yourlabs.remember tasks_from=success
  vars:
    varnames:
    - letsencrypt_email
