---
# Ansible or BigSudo role to setup Drone-CI

- name: Ensure traefik was setup once on this host
  include_role: name=yourlabs.remember tasks_from=require_once
  vars:
    rolename: yourlabs.traefik

- include_role: name=yourlabs.remember tasks_from=questions

- name: Start docker instance
  docker_container:
    name: drone
    image: drone/drone:1
    pull: true
    restart: true
    restart_policy: unless-stopped
    log_driver: journald
    exposed_ports: 80
    networks:
    - name: web
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - drone-data:/var/lib/drone
    labels:
      traefik.enable: 'true'
      traefik.frontend.rule: 'Host:{{ url.split("/")[2] }}'
      traefik.frontend.headers.SSLRedirect: 'true'
      traefik.port: '80'
    env:
      DRONE_GITLAB_SERVER: '{{ gitlab_url }}'
      DRONE_GITLAB_CLIENT_ID: '{{ gitlab_id }}'
      DRONE_GITLAB_CLIENT_SECRET: '{{ gitlab_secret }}'
      DRONE_GITLAB: '{% if gitlab_id %}true{% endif %}'
      DRONE_RUNNER_CAPACITY: '2'
      DRONE_SERVER_HOST: '{{ url.split("/")[2] }}'
      DRONE_SERVER_PROTO: '{{ url.split(":")[0] }}'
      DRONE_TLS_AUTOCERT: 'false'
      DRONE_OPEN: '{% if open and open.lower() != "false" %}true{% else %}false{% endif %}'
      DRONE_DEBUG: 'true'

- include_role: name=yourlabs.remember tasks_from=success
